name: ip
version: 0.1.0
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/terrier989/dart-network
description: A package for working with the IP protocol stack (IPv4, IPv6, ICMP, TCP, UDP).

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: '^0.12.0'
  meta: '^1.0.0'
  raw: '^0.2.0'
  universal_io: '^0.1.1'

dev_dependencies:
  pedantic: '^1.0.0'
  test: '^1.4.0'